### ISSUE TITLE
new development

### ISSUE THREAD

**Issue by Erichliu00** [chi-feng/mcmc-demo#1]
Hi, @chi-feng, thanks for this insightful demo, it helps me a lot for understanding MCMC.
There is a related and interesting [paper](https://github.com/DartML/Stein-Variational-Gradient-Descent) using Stein's method to approximate a target distribution, would it possible to rewrite it in js for online demo?

**Comment by chi-feng** [comment]
That looks like an interesting algorithm and it seems straightforward to implement. I'm currently implementing two other algorithms being worked on by others in my research group and I'll add the SVGD algorithm to the mix. I'll keep this thread updated as I go.
