### ISSUE TITLE
implement funnel distribution

### ISSUE THREAD

**Issue by bob-carpenter** [chi-feng/mcmc-demo#12]
If it's easy to add new distributions, it'd be nice to have Neal's funnel, even if only in 2D.  The density is given by

```
a ~ normal(0, 3)
b ~ normal(0, exp(a / 2))
```

where the normal is taking a scale parameter (std deviation).  The funnel is originally described in this paper:

* Neal, Radford M. 2003. [Slice Sampling](https://projecteuclid.org/download/pdf_1/euclid.aos/1056562461). *Annals of Statistics* 31 (3): 705–67.

P.S.  Thanks for producing this---I direct people to the app all the time.

**Comment by storopoli** [comment]
Neal Funnels would be awesome. I also direct a lot of students to this app all the time.

**Comment by storopoli** [comment]
Thank you! Works like a charm!
