### ISSUE TITLE
Question about the histograms

### ISSUE THREAD

**Issue by HerculesJack** [chi-feng/mcmc-demo#6]
Hi, I was trying the `RadFriends-NS` algorithm on the `multimodal` distribution. I find that after some time, it seems that no new samples are drawn (at least at the two lower peaks), but still the histograms are rapidly changing. Is this a bug or am I missing something here?

**Comment by chi-feng** [comment]
Closed by https://github.com/chi-feng/mcmc-demo/pull/8
